In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3])
print(arr1,arr1.shape)

[1 2 3] (3,)


In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2,arr2.shape) #shape gives no. of rows and columns in an array or matrix

[[1 2 3]
 [4 5 6]] (2, 3)


In [ ]:
arr0=np.zeros((2,3),dtype="int64") #creates a arr with all elements as 0. 1st parameter takes the dimensions
print(arr0,arr0.shape)

arr1=np.ones((2,),dtype="int64") #creates a arr with all elements as 1.
print(arr1,arr1.shape)

arr2=np.eye((2),dtype="int64") #creates an identity matrix. Takes one parameter asking only no. of 1 in diagonal
print(arr2,arr2.shape)

arr3=np.arange(1,11,3) #creates a 1D array of a specific range
print(arr3)

arr4=np.full((2,3),23) #creates a array filled with specific number. 1st parameter is the dimensions and 2nd is the number
print(arr4)

arr5=np.linspace(1,100,6) #creates a 1D array of evenly spaced elements. Here it gives 6 no.s from 1 to 100 distributed evenly.
print(arr5)

[[0 0 0]
 [0 0 0]] (2, 3)
[1 1] (2,)
[[1 0]
 [0 1]] (2, 2)
[ 1  4  7 10]
[[23 23 23]
 [23 23 23]]
[  1.   20.8  40.6  60.4  80.2 100. ]


In [ ]:
#properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape) #gives dimension=mxn
print(arr.size) #gives total no. of elements
print(arr.dtype) #gives the data type of the array
print(arr.ndim) #gives what type of array it is-1D,2D etc.

#Typecasting
arr1=arr.astype(np.float64)
print(arr1,arr1.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [15]:
#operations
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
#1.reshaping
reshape=arr.reshape((3,2))
print(reshape,reshape.shape)
#flatten => convets 2D to 1D
flatten=arr.flatten()
print(flatten,flatten.shape)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [21]:
#2.indexing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1][2])
#fancy indexing
arr=np.array([1,2,3,4,5,6])
idx=[1,2,3]
print(arr[idx])
#boolean inndexing
print(arr[arr>2])
print(arr[arr%2!=0])

6
[2 3 4]
[3 4 5 6]
[1 3 5]


In [ ]:
#3.slicing [Creates a view meaning no new memory space is used to create a copy. Slicing makes a view on original array]
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[::3])
print(arr[1:])
print(arr[:4])

[2 3 4]
[1 4]
[2 3 4 5 6]
[1 2 3 4]


In [28]:
#Multidimensional array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns=np.sum(arr2D,axis=0)
print(sum_of_columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]


In [31]:
#3D Array
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D)
#indexing
print(arr3D[0,1,0])
#slicing
print(arr3D[:,1,:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[[ 3  4]
 [ 9 10]]


In [33]:
#vectorization
arr=np.array([1,2,3,4,5])
print(arr**2)
print(arr+10)

[ 1  4  9 16 25]
[11 12 13 14 15]


In [ ]:
#broadcasting
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1+arr2)
print(arr1.shape,arr2.shape)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
(5,) (2, 5)


In [36]:
#normalization
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
normalized=(arr-mean)/std_dev
print(normalized)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
